-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tqlmate_extract]: function definitions
import Aeneas
import TqlmateExtract.Types
import TqlmateExtract.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/

namespace tqlmate_extract

/-- Trait implementation: [core::fmt::{impl core::fmt::Display for str}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2980:0-2980:20
    Name pattern: [core::fmt::Display<str>] -/
@[reducible, rust_trait_impl "core::fmt::Display<str>"]
def Str.Insts.CoreFmtDisplay : core.fmt.Display Str := {
  fmt := Str.Insts.CoreFmtDisplay.fmt
}

/-- Trait implementation: [core::str::traits::{impl core::cmp::PartialEq<str> for str}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 27:0-27:28
    Name pattern: [core::cmp::PartialEq<str, str>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<str, str>"]
def Str.Insts.CoreCmpPartialEqStr : core.cmp.PartialEq Str Str := {
  eq := Str.Insts.CoreCmpPartialEqStr.eq
}

/-- Trait implementation: [core::str::traits::{impl core::cmp::PartialOrd<str> for str}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 46:0-46:23
    Name pattern: [core::cmp::PartialOrd<str, str>] -/
@[reducible, rust_trait_impl "core::cmp::PartialOrd<str, str>"]
impl_def Str.Insts.CoreCmpPartialOrdStr : core.cmp.PartialOrd Str Str := {
  partialEqInst := Str.Insts.CoreCmpPartialEqStr
  partial_cmp := Str.Insts.CoreCmpPartialOrdStr.partial_cmp
  lt := core.cmp.PartialOrd.lt.default Str.Insts.CoreCmpPartialOrdStr.partial_cmp
  gt := core.cmp.PartialOrd.gt.default Str.Insts.CoreCmpPartialOrdStr.partial_cmp
}

/-- Trait implementation: [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::Range<usize>}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 187:0-187:55
    Name pattern: [core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>] -/
@[reducible, rust_trait_impl
  "core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>"]
def core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr :
  core.slice.index.SliceIndex (core.ops.range.Range Std.Usize) Str Str := {
  get := core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get
  get_mut :=
    core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_mut
  get_unchecked :=
    core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked
  get_unchecked_mut :=
    core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked_mut
  index := core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.index
  index_mut :=
    core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.index_mut
}

/-- Trait implementation: [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeTo<usize>}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 420:0-420:57
    Name pattern: [core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>] -/
@[reducible, rust_trait_impl
  "core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>"]
def core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr :
  core.slice.index.SliceIndex (core.ops.range.RangeTo Std.Usize) Str Str := {
  get := core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get
  get_mut :=
    core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_mut
  get_unchecked :=
    core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked
  get_unchecked_mut :=
    core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked_mut
  index :=
    core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.index
  index_mut :=
    core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.index_mut
}

/-- Trait implementation: [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeFrom<usize>}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 489:0-489:59
    Name pattern: [core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>] -/
@[reducible, rust_trait_impl
  "core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>"]
def core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr :
  core.slice.index.SliceIndex (core.ops.range.RangeFrom Std.Usize) Str Str := {
  get := core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get
  get_mut :=
    core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_mut
  get_unchecked :=
    core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked
  get_unchecked_mut :=
    core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked_mut
  index :=
    core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.index
  index_mut :=
    core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.index_mut
}

/-- Trait implementation: [alloc::string::{impl core::fmt::Debug for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 2754:0-2754:26
    Name pattern: [core::fmt::Debug<alloc::string::String>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<alloc::string::String>"]
def alloc.string.String.Insts.CoreFmtDebug : core.fmt.Debug String := {
  fmt := alloc.string.String.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [alloc::string::{impl core::convert::From<&'_0 str> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 3145:0-3145:26
    Name pattern: [core::convert::From<alloc::string::String, &'0 str>] -/
@[reducible, rust_trait_impl
  "core::convert::From<alloc::string::String, &'0 str>"]
def alloc.string.String.Insts.CoreConvertFromShared0Str : core.convert.From
  String Str := {
  «from» := alloc.string.String.Insts.CoreConvertFromShared0Str.from
}

/-- [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::Version}::fmt]:
    Source: 'src/../../../src/pure.rs', lines 10:9-10:14
    Visibility: public -/
def pure.Version.Insts.CoreFmtDebug.fmt
  (self : pure.Version) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared alloc.string.String.Insts.CoreFmtDebug) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Version") dyn

/-- Trait implementation: [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::Version}]
    Source: 'src/../../../src/pure.rs', lines 10:9-10:14 -/
@[reducible]
def pure.Version.Insts.CoreFmtDebug : core.fmt.Debug pure.Version := {
  fmt := pure.Version.Insts.CoreFmtDebug.fmt
}

/-- [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::Version}::clone]:
    Source: 'src/../../../src/pure.rs', lines 10:16-10:21
    Visibility: public -/
def pure.Version.Insts.CoreCloneClone.clone
  (self : pure.Version) : Result pure.Version := do
  let s ← alloc.string.String.Insts.CoreCloneClone.clone self
  ok s

/-- Trait implementation: [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::Version}]
    Source: 'src/../../../src/pure.rs', lines 10:16-10:21 -/
@[reducible]
def pure.Version.Insts.CoreCloneClone : core.clone.Clone pure.Version := {
  clone := pure.Version.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::StructuralPartialEq for tqlmate_extract::pure::Version}]
    Source: 'src/../../../src/pure.rs', lines 10:23-10:32 -/
@[reducible]
def pure.Version.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq pure.Version := {
}

/-- [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::Version> for tqlmate_extract::pure::Version}::eq]:
    Source: 'src/../../../src/pure.rs', lines 10:23-10:32
    Visibility: public -/
def pure.Version.Insts.CoreCmpPartialEqVersion.eq
  (self : pure.Version) (other : pure.Version) : Result Bool := do
  alloc.string.String.Insts.CoreCmpPartialEqString.eq self other

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::Version> for tqlmate_extract::pure::Version}]
    Source: 'src/../../../src/pure.rs', lines 10:23-10:32 -/
@[reducible]
def pure.Version.Insts.CoreCmpPartialEqVersion : core.cmp.PartialEq
  pure.Version pure.Version := {
  eq := pure.Version.Insts.CoreCmpPartialEqVersion.eq
}

/-- [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::Version}::assert_fields_are_eq]:
    Source: 'src/../../../src/pure.rs', lines 10:34-10:36
    Visibility: public -/
def pure.Version.Insts.CoreCmpEq.assert_fields_are_eq
  (self : pure.Version) : Result Unit := do
  ok ()

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::Version}]
    Source: 'src/../../../src/pure.rs', lines 10:34-10:36 -/
@[reducible]
def pure.Version.Insts.CoreCmpEq : core.cmp.Eq pure.Version := {
  partialEqInst := pure.Version.Insts.CoreCmpPartialEqVersion
  assert_fields_are_eq := pure.Version.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tqlmate_extract::pure::{impl core::cmp::Ord for tqlmate_extract::pure::Version}::cmp]:
    Source: 'src/../../../src/pure.rs', lines 10:50-10:53
    Visibility: public -/
def pure.Version.Insts.CoreCmpOrd.cmp
  (self : pure.Version) (other : pure.Version) : Result Ordering := do
  alloc.string.String.Insts.CoreCmpOrd.cmp self other

/-- [tqlmate_extract::pure::{impl core::cmp::PartialOrd<tqlmate_extract::pure::Version> for tqlmate_extract::pure::Version}::partial_cmp]:
    Source: 'src/../../../src/pure.rs', lines 10:38-10:48
    Visibility: public -/
def pure.Version.Insts.CoreCmpPartialOrdVersion.partial_cmp
  (self : pure.Version) (other : pure.Version) : Result (Option Ordering) := do
  let o ← pure.Version.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::PartialOrd<tqlmate_extract::pure::Version> for tqlmate_extract::pure::Version}]
    Source: 'src/../../../src/pure.rs', lines 10:38-10:48 -/
@[reducible]
impl_def pure.Version.Insts.CoreCmpPartialOrdVersion : core.cmp.PartialOrd
  pure.Version pure.Version := {
  partialEqInst := pure.Version.Insts.CoreCmpPartialEqVersion
  partial_cmp := pure.Version.Insts.CoreCmpPartialOrdVersion.partial_cmp
  lt := core.cmp.PartialOrd.lt.default pure.Version.Insts.CoreCmpPartialOrdVersion.partial_cmp
  gt := core.cmp.PartialOrd.gt.default pure.Version.Insts.CoreCmpPartialOrdVersion.partial_cmp
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::Ord for tqlmate_extract::pure::Version}]
    Source: 'src/../../../src/pure.rs', lines 10:50-10:53 -/
@[reducible]
def pure.Version.Insts.CoreCmpOrd : core.cmp.Ord pure.Version := {
  eqInst := pure.Version.Insts.CoreCmpEq
  partialOrdInst := pure.Version.Insts.CoreCmpPartialOrdVersion
  cmp := pure.Version.Insts.CoreCmpOrd.cmp
}

/-- [tqlmate_extract::pure::{tqlmate_extract::pure::Version}::new]:
    Source: 'src/../../../src/pure.rs', lines 14:4-16:5
    Visibility: public -/
def pure.Version.new
  {T0 : Type} (coreconvertIntoT0StringInst : core.convert.Into T0 String)
  (s : T0) :
  Result pure.Version
  := do
  let s1 ← coreconvertIntoT0StringInst.into s
  ok s1

/-- [tqlmate_extract::pure::{tqlmate_extract::pure::Version}::as_str]:
    Source: 'src/../../../src/pure.rs', lines 18:4-20:5
    Visibility: public -/
def pure.Version.as_str (self : pure.Version) : Result Str := do
  alloc.string.String.Insts.CoreOpsDerefDerefStr.deref self

/-- [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::MigrationId}::fmt]:
    Source: 'src/../../../src/pure.rs', lines 24:9-24:14
    Visibility: public -/
def pure.MigrationId.Insts.CoreFmtDebug.fmt
  (self : pure.MigrationId) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ pure.Version.Insts.CoreFmtDebug self.version
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared alloc.string.String.Insts.CoreFmtDebug)
      self.name
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "MigrationId") (toStr
    "version") dyn (toStr "name") dyn1

/-- Trait implementation: [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::MigrationId}]
    Source: 'src/../../../src/pure.rs', lines 24:9-24:14 -/
@[reducible]
def pure.MigrationId.Insts.CoreFmtDebug : core.fmt.Debug pure.MigrationId := {
  fmt := pure.MigrationId.Insts.CoreFmtDebug.fmt
}

/-- [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::MigrationId}::clone]:
    Source: 'src/../../../src/pure.rs', lines 24:16-24:21
    Visibility: public -/
def pure.MigrationId.Insts.CoreCloneClone.clone
  (self : pure.MigrationId) : Result pure.MigrationId := do
  let v ← pure.Version.Insts.CoreCloneClone.clone self.version
  let s ← alloc.string.String.Insts.CoreCloneClone.clone self.name
  ok { version := v, «name» := s }

/-- Trait implementation: [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::MigrationId}]
    Source: 'src/../../../src/pure.rs', lines 24:16-24:21 -/
@[reducible]
def pure.MigrationId.Insts.CoreCloneClone : core.clone.Clone pure.MigrationId
  := {
  clone := pure.MigrationId.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::StructuralPartialEq for tqlmate_extract::pure::MigrationId}]
    Source: 'src/../../../src/pure.rs', lines 24:23-24:32 -/
@[reducible]
def pure.MigrationId.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq pure.MigrationId := {
}

/-- [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::MigrationId> for tqlmate_extract::pure::MigrationId}::eq]:
    Source: 'src/../../../src/pure.rs', lines 24:23-24:32
    Visibility: public -/
def pure.MigrationId.Insts.CoreCmpPartialEqMigrationId.eq
  (self : pure.MigrationId) (other : pure.MigrationId) : Result Bool := do
  let b ←
    pure.Version.Insts.CoreCmpPartialEqVersion.eq self.version other.version
  if b
  then alloc.string.String.Insts.CoreCmpPartialEqString.eq self.name other.name
  else ok false

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::MigrationId> for tqlmate_extract::pure::MigrationId}]
    Source: 'src/../../../src/pure.rs', lines 24:23-24:32 -/
@[reducible]
def pure.MigrationId.Insts.CoreCmpPartialEqMigrationId : core.cmp.PartialEq
  pure.MigrationId pure.MigrationId := {
  eq := pure.MigrationId.Insts.CoreCmpPartialEqMigrationId.eq
}

/-- [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::MigrationId}::assert_fields_are_eq]:
    Source: 'src/../../../src/pure.rs', lines 24:34-24:36
    Visibility: public -/
def pure.MigrationId.Insts.CoreCmpEq.assert_fields_are_eq
  (self : pure.MigrationId) : Result Unit := do
  ok ()

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::MigrationId}]
    Source: 'src/../../../src/pure.rs', lines 24:34-24:36 -/
@[reducible]
def pure.MigrationId.Insts.CoreCmpEq : core.cmp.Eq pure.MigrationId := {
  partialEqInst := pure.MigrationId.Insts.CoreCmpPartialEqMigrationId
  assert_fields_are_eq := pure.MigrationId.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tqlmate_extract::pure::{tqlmate_extract::pure::MigrationId}::label]:
    Source: 'src/../../../src/pure.rs', lines 31:4-37:5
    Visibility: public -/
def pure.MigrationId.label (self : pure.MigrationId) : Result String := do
  let out ← alloc.string.String.new
  let s := self.version
  let s1 ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref s
  let out1 ← alloc.string.String.push_str out s1
  let out2 ← alloc.string.String.push out1 '_'
  let s2 ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref self.name
  alloc.string.String.push_str out2 s2

/-- [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::MigrationStatus}::fmt]:
    Source: 'src/../../../src/pure.rs', lines 40:9-40:14
    Visibility: public -/
def pure.MigrationStatus.Insts.CoreFmtDebug.fmt
  (self : pure.MigrationStatus) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | pure.MigrationStatus.Applied =>
    core.fmt.Formatter.write_str f (toStr "Applied")
  | pure.MigrationStatus.Pending =>
    core.fmt.Formatter.write_str f (toStr "Pending")

/-- Trait implementation: [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::MigrationStatus}]
    Source: 'src/../../../src/pure.rs', lines 40:9-40:14 -/
@[reducible]
def pure.MigrationStatus.Insts.CoreFmtDebug : core.fmt.Debug
  pure.MigrationStatus := {
  fmt := pure.MigrationStatus.Insts.CoreFmtDebug.fmt
}

/-- [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::MigrationStatus}::clone]:
    Source: 'src/../../../src/pure.rs', lines 40:16-40:21
    Visibility: public -/
def pure.MigrationStatus.Insts.CoreCloneClone.clone
  (self : pure.MigrationStatus) : Result pure.MigrationStatus := do
  ok self

/-- Trait implementation: [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::MigrationStatus}]
    Source: 'src/../../../src/pure.rs', lines 40:16-40:21 -/
@[reducible]
def pure.MigrationStatus.Insts.CoreCloneClone : core.clone.Clone
  pure.MigrationStatus := {
  clone := pure.MigrationStatus.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::Copy for tqlmate_extract::pure::MigrationStatus}]
    Source: 'src/../../../src/pure.rs', lines 40:23-40:27 -/
@[reducible]
def pure.MigrationStatus.Insts.CoreMarkerCopy : core.marker.Copy
  pure.MigrationStatus := {
  cloneInst := pure.MigrationStatus.Insts.CoreCloneClone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::StructuralPartialEq for tqlmate_extract::pure::MigrationStatus}]
    Source: 'src/../../../src/pure.rs', lines 40:29-40:38 -/
@[reducible]
def pure.MigrationStatus.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq pure.MigrationStatus := {
}

/-- [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::MigrationStatus> for tqlmate_extract::pure::MigrationStatus}::eq]:
    Source: 'src/../../../src/pure.rs', lines 40:29-40:38
    Visibility: public -/
def pure.MigrationStatus.Insts.CoreCmpPartialEqMigrationStatus.eq
  (self : pure.MigrationStatus) (other : pure.MigrationStatus) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::MigrationStatus> for tqlmate_extract::pure::MigrationStatus}]
    Source: 'src/../../../src/pure.rs', lines 40:29-40:38 -/
@[reducible]
def pure.MigrationStatus.Insts.CoreCmpPartialEqMigrationStatus :
  core.cmp.PartialEq pure.MigrationStatus pure.MigrationStatus := {
  eq := pure.MigrationStatus.Insts.CoreCmpPartialEqMigrationStatus.eq
}

/-- [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::MigrationStatus}::assert_fields_are_eq]:
    Source: 'src/../../../src/pure.rs', lines 40:40-40:42
    Visibility: public -/
def pure.MigrationStatus.Insts.CoreCmpEq.assert_fields_are_eq
  (self : pure.MigrationStatus) : Result Unit := do
  ok ()

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::MigrationStatus}]
    Source: 'src/../../../src/pure.rs', lines 40:40-40:42 -/
@[reducible]
def pure.MigrationStatus.Insts.CoreCmpEq : core.cmp.Eq pure.MigrationStatus
  := {
  partialEqInst := pure.MigrationStatus.Insts.CoreCmpPartialEqMigrationStatus
  assert_fields_are_eq :=
    pure.MigrationStatus.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::ParseError}::fmt]:
    Source: 'src/../../../src/pure.rs', lines 46:9-46:14
    Visibility: public -/
def pure.ParseError.Insts.CoreFmtDebug.fmt
  (self : pure.ParseError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | pure.ParseError.Extension =>
    core.fmt.Formatter.write_str f (toStr "Extension")
  | pure.ParseError.Filename =>
    core.fmt.Formatter.write_str f (toStr "Filename")
  | pure.ParseError.VersionDigits =>
    core.fmt.Formatter.write_str f (toStr "VersionDigits")
  | pure.ParseError.Name => core.fmt.Formatter.write_str f (toStr "Name")
  | pure.ParseError.Markers => core.fmt.Formatter.write_str f (toStr "Markers")

/-- Trait implementation: [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::ParseError}]
    Source: 'src/../../../src/pure.rs', lines 46:9-46:14 -/
@[reducible]
def pure.ParseError.Insts.CoreFmtDebug : core.fmt.Debug pure.ParseError := {
  fmt := pure.ParseError.Insts.CoreFmtDebug.fmt
}

/-- [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::ParseError}::clone]:
    Source: 'src/../../../src/pure.rs', lines 46:16-46:21
    Visibility: public -/
def pure.ParseError.Insts.CoreCloneClone.clone
  (self : pure.ParseError) : Result pure.ParseError := do
  ok self

/-- Trait implementation: [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::ParseError}]
    Source: 'src/../../../src/pure.rs', lines 46:16-46:21 -/
@[reducible]
def pure.ParseError.Insts.CoreCloneClone : core.clone.Clone pure.ParseError
  := {
  clone := pure.ParseError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::Copy for tqlmate_extract::pure::ParseError}]
    Source: 'src/../../../src/pure.rs', lines 46:23-46:27 -/
@[reducible]
def pure.ParseError.Insts.CoreMarkerCopy : core.marker.Copy pure.ParseError
  := {
  cloneInst := pure.ParseError.Insts.CoreCloneClone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::StructuralPartialEq for tqlmate_extract::pure::ParseError}]
    Source: 'src/../../../src/pure.rs', lines 46:29-46:38 -/
@[reducible]
def pure.ParseError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq pure.ParseError := {
}

/-- [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::ParseError> for tqlmate_extract::pure::ParseError}::eq]:
    Source: 'src/../../../src/pure.rs', lines 46:29-46:38
    Visibility: public -/
def pure.ParseError.Insts.CoreCmpPartialEqParseError.eq
  (self : pure.ParseError) (other : pure.ParseError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::ParseError> for tqlmate_extract::pure::ParseError}]
    Source: 'src/../../../src/pure.rs', lines 46:29-46:38 -/
@[reducible]
def pure.ParseError.Insts.CoreCmpPartialEqParseError : core.cmp.PartialEq
  pure.ParseError pure.ParseError := {
  eq := pure.ParseError.Insts.CoreCmpPartialEqParseError.eq
}

/-- [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::ParseError}::assert_fields_are_eq]:
    Source: 'src/../../../src/pure.rs', lines 46:40-46:42
    Visibility: public -/
def pure.ParseError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : pure.ParseError) : Result Unit := do
  ok ()

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::ParseError}]
    Source: 'src/../../../src/pure.rs', lines 46:40-46:42 -/
@[reducible]
def pure.ParseError.Insts.CoreCmpEq : core.cmp.Eq pure.ParseError := {
  partialEqInst := pure.ParseError.Insts.CoreCmpPartialEqParseError
  assert_fields_are_eq := pure.ParseError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::StrictOrderError}::fmt]:
    Source: 'src/../../../src/pure.rs', lines 55:9-55:14
    Visibility: public -/
def pure.StrictOrderError.Insts.CoreFmtDebug.fmt
  (self : pure.StrictOrderError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let ⟨ __self_0, __self_1 ⟩ := self
  let __self_01 := Dyn.mk _ pure.Version.Insts.CoreFmtDebug __self_0
  let __self_11 :=
    Dyn.mk _ (core.fmt.DebugShared pure.Version.Insts.CoreFmtDebug) __self_1
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "OutOfOrder") (toStr
    "pending") __self_01 (toStr "applied_up_to") __self_11

/-- Trait implementation: [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::StrictOrderError}]
    Source: 'src/../../../src/pure.rs', lines 55:9-55:14 -/
@[reducible]
def pure.StrictOrderError.Insts.CoreFmtDebug : core.fmt.Debug
  pure.StrictOrderError := {
  fmt := pure.StrictOrderError.Insts.CoreFmtDebug.fmt
}

/-- [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::StrictOrderError}::clone]:
    Source: 'src/../../../src/pure.rs', lines 55:16-55:21
    Visibility: public -/
def pure.StrictOrderError.Insts.CoreCloneClone.clone
  (self : pure.StrictOrderError) : Result pure.StrictOrderError := do
  let ⟨ __self_0, __self_1 ⟩ := self
  let v ← pure.Version.Insts.CoreCloneClone.clone __self_0
  let v1 ← pure.Version.Insts.CoreCloneClone.clone __self_1
  ok (pure.StrictOrderError.OutOfOrder v v1)

/-- Trait implementation: [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::StrictOrderError}]
    Source: 'src/../../../src/pure.rs', lines 55:16-55:21 -/
@[reducible]
def pure.StrictOrderError.Insts.CoreCloneClone : core.clone.Clone
  pure.StrictOrderError := {
  clone := pure.StrictOrderError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::StructuralPartialEq for tqlmate_extract::pure::StrictOrderError}]
    Source: 'src/../../../src/pure.rs', lines 55:23-55:32 -/
@[reducible]
def pure.StrictOrderError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq pure.StrictOrderError := {
}

/-- [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::StrictOrderError> for tqlmate_extract::pure::StrictOrderError}::eq]:
    Source: 'src/../../../src/pure.rs', lines 55:23-55:32
    Visibility: public -/
def pure.StrictOrderError.Insts.CoreCmpPartialEqStrictOrderError.eq
  (self : pure.StrictOrderError) (other : pure.StrictOrderError) :
  Result Bool
  := do
  let ⟨ __self_0, __self_1 ⟩ := self
  let ⟨ __arg1_0, __arg1_1 ⟩ := other
  let b ← pure.Version.Insts.CoreCmpPartialEqVersion.eq __self_0 __arg1_0
  if b
  then pure.Version.Insts.CoreCmpPartialEqVersion.eq __self_1 __arg1_1
  else ok false

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::StrictOrderError> for tqlmate_extract::pure::StrictOrderError}]
    Source: 'src/../../../src/pure.rs', lines 55:23-55:32 -/
@[reducible]
def pure.StrictOrderError.Insts.CoreCmpPartialEqStrictOrderError :
  core.cmp.PartialEq pure.StrictOrderError pure.StrictOrderError := {
  eq := pure.StrictOrderError.Insts.CoreCmpPartialEqStrictOrderError.eq
}

/-- [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::StrictOrderError}::assert_fields_are_eq]:
    Source: 'src/../../../src/pure.rs', lines 55:34-55:36
    Visibility: public -/
def pure.StrictOrderError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : pure.StrictOrderError) : Result Unit := do
  ok ()

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::StrictOrderError}]
    Source: 'src/../../../src/pure.rs', lines 55:34-55:36 -/
@[reducible]
def pure.StrictOrderError.Insts.CoreCmpEq : core.cmp.Eq pure.StrictOrderError
  := {
  partialEqInst := pure.StrictOrderError.Insts.CoreCmpPartialEqStrictOrderError
  assert_fields_are_eq :=
    pure.StrictOrderError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::Section}::fmt]:
    Source: 'src/../../../src/pure.rs', lines 63:9-63:14
    Visibility: public -/
def pure.Section.Insts.CoreFmtDebug.fmt
  (self : pure.Section) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | pure.Section.Up => core.fmt.Formatter.write_str f (toStr "Up")
  | pure.Section.Down => core.fmt.Formatter.write_str f (toStr "Down")

/-- Trait implementation: [tqlmate_extract::pure::{impl core::fmt::Debug for tqlmate_extract::pure::Section}]
    Source: 'src/../../../src/pure.rs', lines 63:9-63:14 -/
@[reducible]
def pure.Section.Insts.CoreFmtDebug : core.fmt.Debug pure.Section := {
  fmt := pure.Section.Insts.CoreFmtDebug.fmt
}

/-- [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::Section}::clone]:
    Source: 'src/../../../src/pure.rs', lines 63:16-63:21
    Visibility: public -/
def pure.Section.Insts.CoreCloneClone.clone
  (self : pure.Section) : Result pure.Section := do
  ok self

/-- Trait implementation: [tqlmate_extract::pure::{impl core::clone::Clone for tqlmate_extract::pure::Section}]
    Source: 'src/../../../src/pure.rs', lines 63:16-63:21 -/
@[reducible]
def pure.Section.Insts.CoreCloneClone : core.clone.Clone pure.Section := {
  clone := pure.Section.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::Copy for tqlmate_extract::pure::Section}]
    Source: 'src/../../../src/pure.rs', lines 63:23-63:27 -/
@[reducible]
def pure.Section.Insts.CoreMarkerCopy : core.marker.Copy pure.Section := {
  cloneInst := pure.Section.Insts.CoreCloneClone
}

/-- Trait implementation: [tqlmate_extract::pure::{impl core::marker::StructuralPartialEq for tqlmate_extract::pure::Section}]
    Source: 'src/../../../src/pure.rs', lines 63:29-63:38 -/
@[reducible]
def pure.Section.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq pure.Section := {
}

/-- [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::Section> for tqlmate_extract::pure::Section}::eq]:
    Source: 'src/../../../src/pure.rs', lines 63:29-63:38
    Visibility: public -/
def pure.Section.Insts.CoreCmpPartialEqSection.eq
  (self : pure.Section) (other : pure.Section) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::PartialEq<tqlmate_extract::pure::Section> for tqlmate_extract::pure::Section}]
    Source: 'src/../../../src/pure.rs', lines 63:29-63:38 -/
@[reducible]
def pure.Section.Insts.CoreCmpPartialEqSection : core.cmp.PartialEq
  pure.Section pure.Section := {
  eq := pure.Section.Insts.CoreCmpPartialEqSection.eq
}

/-- [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::Section}::assert_fields_are_eq]:
    Source: 'src/../../../src/pure.rs', lines 63:40-63:42
    Visibility: public -/
def pure.Section.Insts.CoreCmpEq.assert_fields_are_eq
  (self : pure.Section) : Result Unit := do
  ok ()

/-- Trait implementation: [tqlmate_extract::pure::{impl core::cmp::Eq for tqlmate_extract::pure::Section}]
    Source: 'src/../../../src/pure.rs', lines 63:40-63:42 -/
@[reducible]
def pure.Section.Insts.CoreCmpEq : core.cmp.Eq pure.Section := {
  partialEqInst := pure.Section.Insts.CoreCmpPartialEqSection
  assert_fields_are_eq := pure.Section.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tqlmate_extract::pure::has_suffix]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 77:4-84:1 -/
@[rust_loop_body]
def pure.has_suffix_loop.body
  (sb : Slice Std.U8) (suf : Slice Std.U8) (start : Std.Usize) (i : Std.Usize)
  :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len suf
  if i < i1
  then
    let i2 ← start + i
    let i3 ← Slice.index_usize sb i2
    let i4 ← Slice.index_usize suf i
    if i3 != i4
    then ok (done false)
    else let i5 ← i + 1#usize
         ok (cont i5)
  else ok (done true)

/-- [tqlmate_extract::pure::has_suffix]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 77:4-84:1 -/
@[rust_loop]
def pure.has_suffix_loop
  (sb : Slice Std.U8) (suf : Slice Std.U8) (start : Std.Usize) (i : Std.Usize)
  :
  Result Bool
  := do
  loop
    (fun i1 => pure.has_suffix_loop.body sb suf start i1)
    i

/-- [tqlmate_extract::pure::has_suffix]:
    Source: 'src/../../../src/pure.rs', lines 69:0-84:1 -/
def pure.has_suffix (s : Str) (suffix : Str) : Result Bool := do
  let sb ← core.str.Str.as_bytes s
  let suf ← core.str.Str.as_bytes suffix
  let i := Slice.len sb
  let i1 := Slice.len suf
  if i < i1
  then ok false
  else
    let i2 := Slice.len sb
    let i3 := Slice.len suf
    let start ← i2 - i3
    pure.has_suffix_loop sb suf start 0#usize

/-- [tqlmate_extract::pure::drop_suffix]:
    Source: 'src/../../../src/pure.rs', lines 86:0-92:1 -/
def pure.drop_suffix (s : Str) (suffix : Str) : Result (Option Str) := do
  let b ← pure.has_suffix s suffix
  if b
  then
    let i ← core.str.Str.len s
    let i1 ← core.str.Str.len suffix
    let i2 ← i - i1
    let s1 ←
      Str.Insts.CoreOpsIndexIndex.index
        core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr s
        { «end» := i2 }
    ok (some s1)
  else ok none

/-- [tqlmate_extract::pure::has_prefix]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 101:4-108:1 -/
@[rust_loop_body]
def pure.has_prefix_loop.body
  (sb : Slice Std.U8) (pre : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len pre
  if i < i1
  then
    let i2 ← Slice.index_usize sb i
    let i3 ← Slice.index_usize pre i
    if i2 != i3
    then ok (done false)
    else let i4 ← i + 1#usize
         ok (cont i4)
  else ok (done true)

/-- [tqlmate_extract::pure::has_prefix]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 101:4-108:1 -/
@[rust_loop]
def pure.has_prefix_loop
  (sb : Slice Std.U8) (pre : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => pure.has_prefix_loop.body sb pre i1)
    i

/-- [tqlmate_extract::pure::has_prefix]:
    Source: 'src/../../../src/pure.rs', lines 94:0-108:1 -/
def pure.has_prefix (s : Str) («prefix» : Str) : Result Bool := do
  let sb ← core.str.Str.as_bytes s
  let pre ← core.str.Str.as_bytes «prefix»
  let i := Slice.len sb
  let i1 := Slice.len pre
  if i < i1
  then ok false
  else pure.has_prefix_loop sb pre 0#usize

/-- [tqlmate_extract::pure::drop_prefix]:
    Source: 'src/../../../src/pure.rs', lines 110:0-116:1 -/
def pure.drop_prefix (s : Str) («prefix» : Str) : Result (Option Str) := do
  let b ← pure.has_prefix s «prefix»
  if b
  then
    let i ← core.str.Str.len «prefix»
    let s1 ←
      Str.Insts.CoreOpsIndexIndex.index
        core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr s
        { start := i }
    ok (some s1)
  else ok none

/-- [tqlmate_extract::pure::find_byte]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 121:4-128:1 -/
@[rust_loop_body]
def pure.find_byte_loop.body
  (b : Std.U8) (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize (Option Std.Usize))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    if i2 = b
    then ok (done (some i))
    else let i3 ← i + 1#usize
         ok (cont i3)
  else ok (done none)

/-- [tqlmate_extract::pure::find_byte]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 121:4-128:1 -/
@[rust_loop]
def pure.find_byte_loop
  (b : Std.U8) (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (Option Std.Usize)
  := do
  loop
    (fun i1 => pure.find_byte_loop.body b bytes i1)
    i

/-- [tqlmate_extract::pure::find_byte]:
    Source: 'src/../../../src/pure.rs', lines 118:0-128:1 -/
def pure.find_byte (s : Str) (b : Std.U8) : Result (Option Std.Usize) := do
  let bytes ← core.str.Str.as_bytes s
  pure.find_byte_loop b bytes 0#usize

/-- [tqlmate_extract::pure::split_once_char]:
    Source: 'src/../../../src/pure.rs', lines 130:0-135:1 -/
def pure.split_once_char
  (s : Str) (sep : Std.U8) : Result (Option (Str × Str)) := do
  let o ← pure.find_byte s sep
  match o with
  | none => ok none
  | some i =>
    let s1 ←
      Str.Insts.CoreOpsIndexIndex.index
        core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr s
        { «end» := i }
    let i1 ← i + 1#usize
    let s2 ←
      Str.Insts.CoreOpsIndexIndex.index
        core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr s
        { start := i1 }
    ok (some (s1, s2))

/-- [tqlmate_extract::pure::trim_spaces]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 140:4-142:5 -/
@[rust_loop_body]
def pure.trim_spaces_loop0.body
  (bytes : Slice Std.U8) (start : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len bytes
  if start < i
  then
    let i1 ← Slice.index_usize bytes start
    if i1 = 32#u8
    then let start1 ← start + 1#usize
         ok (cont start1)
    else
      if i1 = 9#u8
      then let start1 ← start + 1#usize
           ok (cont start1)
      else ok (done start)
  else ok (done start)

/-- [tqlmate_extract::pure::trim_spaces]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 140:4-142:5 -/
@[rust_loop]
def pure.trim_spaces_loop0
  (bytes : Slice Std.U8) (start : Std.Usize) : Result Std.Usize := do
  loop
    (fun start1 => pure.trim_spaces_loop0.body bytes start1)
    start

/-- [tqlmate_extract::pure::trim_spaces]: loop body 1:
    Source: 'src/../../../src/pure.rs', lines 144:4-146:5 -/
@[rust_loop_body]
def pure.trim_spaces_loop1.body
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if «end» > start
  then
    let i ← «end» - 1#usize
    let i1 ← Slice.index_usize bytes i
    if i1 = 32#u8
    then ok (cont i)
    else
      let i2 ← Slice.index_usize bytes i
      if i2 = 9#u8
      then ok (cont i)
      else ok (done «end»)
  else ok (done «end»)

/-- [tqlmate_extract::pure::trim_spaces]: loop 1:
    Source: 'src/../../../src/pure.rs', lines 144:4-146:5 -/
@[rust_loop]
def pure.trim_spaces_loop1
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun end1 => pure.trim_spaces_loop1.body bytes start end1)
    «end»

/-- [tqlmate_extract::pure::trim_spaces]:
    Source: 'src/../../../src/pure.rs', lines 137:0-148:1 -/
def pure.trim_spaces (s : Str) : Result Str := do
  let bytes ← core.str.Str.as_bytes s
  let start ← pure.trim_spaces_loop0 bytes 0#usize
  let «end» := Slice.len bytes
  let end1 ← pure.trim_spaces_loop1 bytes start «end»
  Str.Insts.CoreOpsIndexIndex.index
    core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr s
    { start, «end» := end1 }

/-- [tqlmate_extract::pure::trim_underscores]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 153:4-155:5 -/
@[rust_loop_body]
def pure.trim_underscores_loop0.body
  (bytes : Slice Std.U8) (start : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len bytes
  if start < i
  then
    let i1 ← Slice.index_usize bytes start
    if i1 = 95#u8
    then let start1 ← start + 1#usize
         ok (cont start1)
    else ok (done start)
  else ok (done start)

/-- [tqlmate_extract::pure::trim_underscores]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 153:4-155:5 -/
@[rust_loop]
def pure.trim_underscores_loop0
  (bytes : Slice Std.U8) (start : Std.Usize) : Result Std.Usize := do
  loop
    (fun start1 => pure.trim_underscores_loop0.body bytes start1)
    start

/-- [tqlmate_extract::pure::trim_underscores]: loop body 1:
    Source: 'src/../../../src/pure.rs', lines 157:4-159:5 -/
@[rust_loop_body]
def pure.trim_underscores_loop1.body
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if «end» > start
  then
    let i ← «end» - 1#usize
    let i1 ← Slice.index_usize bytes i
    if i1 = 95#u8
    then ok (cont i)
    else ok (done «end»)
  else ok (done «end»)

/-- [tqlmate_extract::pure::trim_underscores]: loop 1:
    Source: 'src/../../../src/pure.rs', lines 157:4-159:5 -/
@[rust_loop]
def pure.trim_underscores_loop1
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun end1 => pure.trim_underscores_loop1.body bytes start end1)
    «end»

/-- [tqlmate_extract::pure::trim_underscores]:
    Source: 'src/../../../src/pure.rs', lines 150:0-161:1 -/
def pure.trim_underscores (s : Str) : Result Str := do
  let bytes ← core.str.Str.as_bytes s
  let start ← pure.trim_underscores_loop0 bytes 0#usize
  let «end» := Slice.len bytes
  let end1 ← pure.trim_underscores_loop1 bytes start «end»
  Str.Insts.CoreOpsIndexIndex.index
    core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr s
    { start, «end» := end1 }

/-- [tqlmate_extract::pure::ends_with_underscore]:
    Source: 'src/../../../src/pure.rs', lines 163:0-166:1 -/
def pure.ends_with_underscore (s : Str) : Result Bool := do
  let bytes ← core.str.Str.as_bytes s
  let b ← core.slice.Slice.is_empty bytes
  if b
  then ok false
  else
    let i := Slice.len bytes
    let i1 ← i - 1#usize
    let i2 ← Slice.index_usize bytes i1
    ok (i2 = 95#u8)

/-- [tqlmate_extract::pure::ascii_lower]:
    Source: 'src/../../../src/pure.rs', lines 168:0-174:1 -/
def pure.ascii_lower (c : Std.U8) : Result Std.U8 := do
  if c >= 65#u8
  then if c <= 90#u8
       then c + 32#u8
       else ok c
  else ok c

/-- [tqlmate_extract::pure::eq_ignore_ascii_case]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 183:4-190:1 -/
@[rust_loop_body]
def pure.eq_ignore_ascii_case_loop.body
  (ab : Slice Std.U8) (bb : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len ab
  if i < i1
  then
    let i2 ← Slice.index_usize ab i
    let i3 ← pure.ascii_lower i2
    let i4 ← Slice.index_usize bb i
    let i5 ← pure.ascii_lower i4
    if i3 != i5
    then ok (done false)
    else let i6 ← i + 1#usize
         ok (cont i6)
  else ok (done true)

/-- [tqlmate_extract::pure::eq_ignore_ascii_case]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 183:4-190:1 -/
@[rust_loop]
def pure.eq_ignore_ascii_case_loop
  (ab : Slice Std.U8) (bb : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => pure.eq_ignore_ascii_case_loop.body ab bb i1)
    i

/-- [tqlmate_extract::pure::eq_ignore_ascii_case]:
    Source: 'src/../../../src/pure.rs', lines 176:0-190:1 -/
def pure.eq_ignore_ascii_case (a : Str) (b : Str) : Result Bool := do
  let ab ← core.str.Str.as_bytes a
  let bb ← core.str.Str.as_bytes b
  let i := Slice.len ab
  let i1 := Slice.len bb
  if i != i1
  then ok false
  else pure.eq_ignore_ascii_case_loop ab bb 0#usize

/-- [tqlmate_extract::pure::is_ascii_digit_byte]:
    Source: 'src/../../../src/pure.rs', lines 192:0-194:1 -/
def pure.is_ascii_digit_byte (c : Std.U8) : Result Bool := do
  if c >= 48#u8
  then ok (c <= 57#u8)
  else ok false

/-- [tqlmate_extract::pure::is_ascii_digits]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 202:4-209:1 -/
@[rust_loop_body]
def pure.is_ascii_digits_loop.body
  (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let b ← pure.is_ascii_digit_byte i2
    if b
    then let i3 ← i + 1#usize
         ok (cont i3)
    else ok (done false)
  else ok (done true)

/-- [tqlmate_extract::pure::is_ascii_digits]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 202:4-209:1 -/
@[rust_loop]
def pure.is_ascii_digits_loop
  (bytes : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => pure.is_ascii_digits_loop.body bytes i1)
    i

/-- [tqlmate_extract::pure::is_ascii_digits]:
    Source: 'src/../../../src/pure.rs', lines 196:0-209:1 -/
def pure.is_ascii_digits (s : Str) : Result Bool := do
  let bytes ← core.str.Str.as_bytes s
  let b ← core.slice.Slice.is_empty bytes
  if b
  then ok false
  else pure.is_ascii_digits_loop bytes 0#usize

/-- [tqlmate_extract::pure::is_ascii_alnum_byte]:
    Source: 'src/../../../src/pure.rs', lines 211:0-213:1 -/
def pure.is_ascii_alnum_byte (c : Std.U8) : Result Bool := do
  let b ← pure.is_ascii_digit_byte c
  if b
  then ok true
  else
    if c >= 97#u8
    then
      if c <= 122#u8
      then ok true
      else if c >= 65#u8
           then ok (c <= 90#u8)
           else ok false
    else if c >= 65#u8
         then ok (c <= 90#u8)
         else ok false

/-- [tqlmate_extract::pure::parse_version_name]:
    Source: 'src/../../../src/pure.rs', lines 216:0-232:1
    Visibility: public -/
def pure.parse_version_name
  (filename : Str) :
  Result (core.result.Result (pure.Version × String) pure.ParseError)
  := do
  let o ← pure.drop_suffix filename (toStr ".tql")
  match o with
  | none => ok (core.result.Result.Err pure.ParseError.Extension)
  | some s =>
    let o1 ← pure.split_once_char s 95#u8
    match o1 with
    | none => ok (core.result.Result.Err pure.ParseError.Filename)
    | some p =>
      let (version, rest) := p
      let b ← core.str.Str.is_empty version
      if b
      then ok (core.result.Result.Err pure.ParseError.VersionDigits)
      else
        let b1 ← pure.is_ascii_digits version
        if b1
        then
          let b2 ← core.str.Str.is_empty rest
          if b2
          then ok (core.result.Result.Err pure.ParseError.Name)
          else
            let v ←
              pure.Version.new (core.convert.IntoFrom
                alloc.string.String.Insts.CoreConvertFromShared0Str) version
            let s1 ←
              alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay
                rest
            ok (core.result.Result.Ok (v, s1))
        else ok (core.result.Result.Err pure.ParseError.VersionDigits)

/-- [tqlmate_extract::pure::migration_marker]:
    Source: 'src/../../../src/pure.rs', lines 302:0-313:1 -/
def pure.migration_marker (line : Str) : Result (Option pure.Section) := do
  let trimmed ← pure.trim_spaces line
  let o ← pure.drop_prefix trimmed (toStr "--")
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let marker ← pure.trim_spaces val
    let b ← pure.eq_ignore_ascii_case marker (toStr "migrate:up")
    if b
    then ok (some pure.Section.Up)
    else
      let b1 ← pure.eq_ignore_ascii_case marker (toStr "migrate:down")
      if b1
      then ok (some pure.Section.Down)
      else ok none
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      pure.Section residual

/-- [tqlmate_extract::pure::is_ascii_ws]:
    Source: 'src/../../../src/pure.rs', lines 298:0-300:1 -/
def pure.is_ascii_ws (c : Std.U8) : Result Bool := do
  if c = 32#u8
  then ok true
  else
    if c = 9#u8
    then ok true
    else if c = 10#u8
         then ok true
         else ok (c = 13#u8)

/-- [tqlmate_extract::pure::trim_owned]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 288:4-290:5 -/
@[rust_loop_body]
def pure.trim_owned_loop0.body
  (bytes : Slice Std.U8) (start : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len bytes
  if start < i
  then
    let i1 ← Slice.index_usize bytes start
    let b ← pure.is_ascii_ws i1
    if b
    then let start1 ← start + 1#usize
         ok (cont start1)
    else ok (done start)
  else ok (done start)

/-- [tqlmate_extract::pure::trim_owned]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 288:4-290:5 -/
@[rust_loop]
def pure.trim_owned_loop0
  (bytes : Slice Std.U8) (start : Std.Usize) : Result Std.Usize := do
  loop
    (fun start1 => pure.trim_owned_loop0.body bytes start1)
    start

/-- [tqlmate_extract::pure::trim_owned]: loop body 1:
    Source: 'src/../../../src/pure.rs', lines 292:4-294:5 -/
@[rust_loop_body]
def pure.trim_owned_loop1.body
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if «end» > start
  then
    let i ← «end» - 1#usize
    let i1 ← Slice.index_usize bytes i
    let b ← pure.is_ascii_ws i1
    if b
    then ok (cont i)
    else ok (done «end»)
  else ok (done «end»)

/-- [tqlmate_extract::pure::trim_owned]: loop 1:
    Source: 'src/../../../src/pure.rs', lines 292:4-294:5 -/
@[rust_loop]
def pure.trim_owned_loop1
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun end1 => pure.trim_owned_loop1.body bytes start end1)
    «end»

/-- [tqlmate_extract::pure::trim_owned]:
    Source: 'src/../../../src/pure.rs', lines 284:0-296:1 -/
def pure.trim_owned (s : String) : Result String := do
  let bytes ← alloc.string.String.as_bytes s
  let start ← pure.trim_owned_loop0 bytes 0#usize
  let «end» := Slice.len bytes
  let end1 ← pure.trim_owned_loop1 bytes start «end»
  let s1 ←
    alloc.string.String.Insts.CoreOpsIndexIndex.index
      core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr s
      { start, «end» := end1 }
  alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay s1

/-- [tqlmate_extract::pure::split_up_down]: loop body 1:
    Source: 'src/../../../src/pure.rs', lines 246:8-248:9
    Visibility: public -/
@[rust_loop_body]
def pure.split_up_down_loop0_loop0.body
  (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    if i2 != 10#u8
    then let i3 ← i + 1#usize
         ok (cont i3)
    else ok (done i)
  else ok (done i)

/-- [tqlmate_extract::pure::split_up_down]: loop 1:
    Source: 'src/../../../src/pure.rs', lines 246:8-248:9
    Visibility: public -/
@[rust_loop]
def pure.split_up_down_loop0_loop0
  (bytes : Slice Std.U8) (i : Std.Usize) : Result Std.Usize := do
  loop
    (fun i1 => pure.split_up_down_loop0_loop0.body bytes i1)
    i

/-- [tqlmate_extract::pure::split_up_down]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 244:4-276:5
    Visibility: public -/
@[rust_loop_body]
def pure.split_up_down_loop0.body
  (text : Str) (bytes : Slice Std.U8) («section» : Option pure.Section)
  (up : String) (down : String) (saw_marker : Bool) (i : Std.Usize) :
  Result (ControlFlow ((Option pure.Section) × String × String × Bool ×
    Std.Usize) (String × String × Bool))
  := do
  let i1 := Slice.len bytes
  if i <= i1
  then
    let «end» ← pure.split_up_down_loop0_loop0 bytes i
    let end1 ←
      if «end» > i
      then
        do
        let i2 ← «end» - 1#usize
        let i3 ← Slice.index_usize bytes i2
        if i3 = 13#u8
        then ok i2
        else ok «end»
      else ok «end»
    let line ←
      Str.Insts.CoreOpsIndexIndex.index
        core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr text
        { start := i, «end» := end1 }
    let o ← pure.migration_marker line
    let (section1, up1, down1, saw_marker1) ←
      match o with
      | none =>
        do
        let (o1, s, s1) ←
          match «section» with
          | none => ok (none, up, down)
          | some s2 =>
            do
            let (s3, s4) ←
              match s2 with
              | pure.Section.Up =>
                do
                let up2 ← alloc.string.String.push_str up line
                let up3 ← alloc.string.String.push up2 '
'
                ok (up3, down)
              | pure.Section.Down =>
                do
                let down2 ← alloc.string.String.push_str down line
                let down3 ← alloc.string.String.push down2 '
'
                ok (up, down3)
            ok («section», s3, s4)
        ok (o1, s, s1, saw_marker)
      | some _ => ok (o, up, down, true)
    let i2 := Slice.len bytes
    if «end» < i2
    then
      let i3 ← «end» + 1#usize
      ok (cont (section1, up1, down1, saw_marker1, i3))
    else ok (done (up1, down1, saw_marker1))
  else ok (done (up, down, saw_marker))

/-- [tqlmate_extract::pure::split_up_down]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 244:4-276:5
    Visibility: public -/
@[rust_loop]
def pure.split_up_down_loop0
  (text : Str) («section» : Option pure.Section) (up : String)
  (down : String) (saw_marker : Bool) (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (String × String × Bool)
  := do
  loop
    (fun (section1, up1, down1, saw_marker1, i1) =>
      pure.split_up_down_loop0.body text bytes section1 up1 down1 saw_marker1
      i1)
    («section», up, down, saw_marker, i)

/-- [tqlmate_extract::pure::split_up_down]:
    Source: 'src/../../../src/pure.rs', lines 235:0-282:1
    Visibility: public -/
def pure.split_up_down
  (text : Str) :
  Result (core.result.Result (String × String) pure.ParseError)
  := do
  let up ← alloc.string.String.new
  let bytes ← core.str.Str.as_bytes text
  let (up1, down, saw_marker) ←
    pure.split_up_down_loop0 text none up up false bytes 0#usize
  if saw_marker
  then
    let s ← pure.trim_owned up1
    let s1 ← pure.trim_owned down
    ok (core.result.Result.Ok (s, s1))
  else
    let b ← alloc.string.String.is_empty up1
    if b
    then
      let b1 ← alloc.string.String.is_empty down
      if b1
      then ok (core.result.Result.Err pure.ParseError.Markers)
      else
        let s ← pure.trim_owned up1
        let s1 ← pure.trim_owned down
        ok (core.result.Result.Ok (s, s1))
    else
      let s ← pure.trim_owned up1
      let s1 ← pure.trim_owned down
      ok (core.result.Result.Ok (s, s1))

/-- [tqlmate_extract::pure::version_in]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 334:4-341:1 -/
@[rust_loop_body]
def pure.version_in_loop.body
  (applied : Slice pure.Version) (v : pure.Version) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len applied
  if i < i1
  then
    let v1 ← Slice.index_usize applied i
    let b ← pure.Version.Insts.CoreCmpPartialEqVersion.eq v1 v
    if b
    then ok (done true)
    else let i2 ← i + 1#usize
         ok (cont i2)
  else ok (done false)

/-- [tqlmate_extract::pure::version_in]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 334:4-341:1 -/
@[rust_loop]
def pure.version_in_loop
  (applied : Slice pure.Version) (v : pure.Version) (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => pure.version_in_loop.body applied v i1)
    i

/-- [tqlmate_extract::pure::version_in]:
    Source: 'src/../../../src/pure.rs', lines 332:0-341:1 -/
@[reducible]
def pure.version_in
  (applied : Slice pure.Version) (v : pure.Version) : Result Bool := do
  pure.version_in_loop applied v 0#usize

/-- [tqlmate_extract::pure::status_rows]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 319:4-328:5
    Visibility: public -/
@[rust_loop_body]
def pure.status_rows_loop.body
  (files : Slice pure.MigrationId) (applied : Slice pure.Version)
  (out : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (pure.MigrationId ×
    pure.MigrationStatus)) × Std.Usize) (alloc.vec.Vec (pure.MigrationId ×
    pure.MigrationStatus)))
  := do
  let i1 := Slice.len files
  if i < i1
  then
    let mi ← Slice.index_usize files i
    let f ← pure.MigrationId.Insts.CoreCloneClone.clone mi
    let b ← pure.version_in applied f.version
    let status ←
      if b
      then ok pure.MigrationStatus.Applied
      else ok pure.MigrationStatus.Pending
    let out1 ← alloc.vec.Vec.push out (f, status)
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [tqlmate_extract::pure::status_rows]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 319:4-328:5
    Visibility: public -/
@[rust_loop]
def pure.status_rows_loop
  (files : Slice pure.MigrationId) (applied : Slice pure.Version)
  (out : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (i : Std.Usize) :
  Result (alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  := do
  loop
    (fun (out1, i1) => pure.status_rows_loop.body files applied out1 i1)
    (out, i)

/-- [tqlmate_extract::pure::status_rows]:
    Source: 'src/../../../src/pure.rs', lines 316:0-330:1
    Visibility: public -/
@[reducible]
def pure.status_rows
  (files : Slice pure.MigrationId) (applied : Slice pure.Version) :
  Result (alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  := do
  pure.status_rows_loop files applied (alloc.vec.Vec.new (pure.MigrationId ×
    pure.MigrationStatus)) 0#usize

/-- [tqlmate_extract::pure::pending_versions]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 348:4-357:5
    Visibility: public -/
@[rust_loop_body]
def pure.pending_versions_loop.body
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (out : alloc.vec.Vec pure.Version) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec pure.Version) × Std.Usize)
    (alloc.vec.Vec pure.Version))
  := do
  let i1 := alloc.vec.Vec.len rows
  if i < i1
  then
    let p ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        (pure.MigrationId × pure.MigrationStatus)) rows i
    let (id, status) ←
      (BuiltinClone (pure.MigrationId × pure.MigrationStatus)).clone p
    let out1 ←
      match status with
      | pure.MigrationStatus.Applied => ok out
      | pure.MigrationStatus.Pending => alloc.vec.Vec.push out id.version
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [tqlmate_extract::pure::pending_versions]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 348:4-357:5
    Visibility: public -/
@[rust_loop]
def pure.pending_versions_loop
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (out : alloc.vec.Vec pure.Version) (i : Std.Usize) :
  Result (alloc.vec.Vec pure.Version)
  := do
  loop
    (fun (out1, i1) => pure.pending_versions_loop.body rows out1 i1)
    (out, i)

/-- [tqlmate_extract::pure::pending_versions]:
    Source: 'src/../../../src/pure.rs', lines 344:0-359:1
    Visibility: public -/
def pure.pending_versions
  (files : Slice pure.MigrationId) (applied : Slice pure.Version) :
  Result (alloc.vec.Vec pure.Version)
  := do
  let rows ← pure.status_rows files applied
  pure.pending_versions_loop rows (alloc.vec.Vec.new pure.Version) 0#usize

/-- [tqlmate_extract::pure::applied_among]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 366:4-375:5
    Visibility: public -/
@[rust_loop_body]
def pure.applied_among_loop.body
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (out : alloc.vec.Vec pure.Version) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec pure.Version) × Std.Usize)
    (alloc.vec.Vec pure.Version))
  := do
  let i1 := alloc.vec.Vec.len rows
  if i < i1
  then
    let p ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        (pure.MigrationId × pure.MigrationStatus)) rows i
    let (id, status) ←
      (BuiltinClone (pure.MigrationId × pure.MigrationStatus)).clone p
    let out1 ←
      match status with
      | pure.MigrationStatus.Applied => alloc.vec.Vec.push out id.version
      | pure.MigrationStatus.Pending => ok out
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [tqlmate_extract::pure::applied_among]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 366:4-375:5
    Visibility: public -/
@[rust_loop]
def pure.applied_among_loop
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (out : alloc.vec.Vec pure.Version) (i : Std.Usize) :
  Result (alloc.vec.Vec pure.Version)
  := do
  loop
    (fun (out1, i1) => pure.applied_among_loop.body rows out1 i1)
    (out, i)

/-- [tqlmate_extract::pure::applied_among]:
    Source: 'src/../../../src/pure.rs', lines 362:0-377:1
    Visibility: public -/
def pure.applied_among
  (files : Slice pure.MigrationId) (applied : Slice pure.Version) :
  Result (alloc.vec.Vec pure.Version)
  := do
  let rows ← pure.status_rows files applied
  pure.applied_among_loop rows (alloc.vec.Vec.new pure.Version) 0#usize

/-- [tqlmate_extract::pure::pending_applied_disjoint]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 386:4-393:5
    Visibility: public -/
@[rust_loop_body]
def pure.pending_applied_disjoint_loop0.body
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Unit)
  := do
  let i1 := alloc.vec.Vec.len rows
  if i < i1
  then
    let _ ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        (pure.MigrationId × pure.MigrationStatus)) rows i
    let i2 ← i + 1#usize
    ok (cont i2)
  else ok (done ())

/-- [tqlmate_extract::pure::pending_applied_disjoint]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 386:4-393:5
    Visibility: public -/
@[rust_loop]
def pure.pending_applied_disjoint_loop0
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (i : Std.Usize) :
  Result Unit
  := do
  loop
    (fun i1 => pure.pending_applied_disjoint_loop0.body rows i1)
    i

/-- [tqlmate_extract::pure::pending_applied_disjoint]: loop body 1:
    Source: 'src/../../../src/pure.rs', lines 396:4-411:5
    Visibility: public -/
@[rust_loop_body]
def pure.pending_applied_disjoint_loop1.body
  (applied : Slice pure.Version)
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (i : Std.Usize) (ok1 : Bool) :
  Result (ControlFlow (Std.Usize × Bool) Bool)
  := do
  let i1 := alloc.vec.Vec.len rows
  if i < i1
  then
    let (mi, ms) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        (pure.MigrationId × pure.MigrationStatus)) rows i
    let in_applied ← pure.version_in applied mi.version
    let ok2 ←
      match ms with
      | pure.MigrationStatus.Applied => if in_applied
                                        then ok ok1
                                        else ok false
      | pure.MigrationStatus.Pending => if in_applied
                                        then ok false
                                        else ok ok1
    let i2 ← i + 1#usize
    ok (cont (i2, ok2))
  else ok (done ok1)

/-- [tqlmate_extract::pure::pending_applied_disjoint]: loop 1:
    Source: 'src/../../../src/pure.rs', lines 396:4-411:5
    Visibility: public -/
@[rust_loop]
def pure.pending_applied_disjoint_loop1
  (applied : Slice pure.Version)
  (rows : alloc.vec.Vec (pure.MigrationId × pure.MigrationStatus))
  (i : Std.Usize) (ok1 : Bool) :
  Result Bool
  := do
  loop
    (fun (i1, ok2) => pure.pending_applied_disjoint_loop1.body applied rows i1
      ok2)
    (i, ok1)

/-- [tqlmate_extract::pure::pending_applied_disjoint]:
    Source: 'src/../../../src/pure.rs', lines 382:0-413:1
    Visibility: public -/
def pure.pending_applied_disjoint
  (files : Slice pure.MigrationId) (applied : Slice pure.Version) :
  Result Bool
  := do
  let rows ← pure.status_rows files applied
  pure.pending_applied_disjoint_loop0 rows 0#usize
  pure.pending_applied_disjoint_loop1 applied rows 0#usize true

/-- [tqlmate_extract::pure::max_version]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 448:4-453:5 -/
@[rust_loop_body]
def pure.max_version_loop.body
  (applied : Slice pure.Version) (best : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Std.Usize)
  := do
  let i1 := Slice.len applied
  if i < i1
  then
    let v ← Slice.index_usize applied i
    let v1 ← Slice.index_usize applied best
    let b ←
      core.cmp.PartialOrd.gt.default pure.Version.Insts.CoreCmpPartialOrdVersion.partial_cmp v v1
    let best1 ← if b
                  then ok i
                  else ok best
    let i2 ← i + 1#usize
    ok (cont (best1, i2))
  else ok (done best)

/-- [tqlmate_extract::pure::max_version]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 448:4-453:5 -/
@[rust_loop]
def pure.max_version_loop
  (applied : Slice pure.Version) (best : Std.Usize) (i : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (best1, i1) => pure.max_version_loop.body applied best1 i1)
    (best, i)

/-- [tqlmate_extract::pure::max_version]:
    Source: 'src/../../../src/pure.rs', lines 442:0-455:1 -/
def pure.max_version
  (applied : Slice pure.Version) : Result (Option pure.Version) := do
  let b ← core.slice.Slice.is_empty applied
  if b
  then ok none
  else
    let best ← pure.max_version_loop applied 0#usize 1#usize
    let v ← Slice.index_usize applied best
    let v1 ← pure.Version.Insts.CoreCloneClone.clone v
    ok (some v1)

/-- [tqlmate_extract::pure::str_lt]:
    Source: 'src/../../../src/pure.rs', lines 438:0-440:1 -/
def pure.str_lt (a : Str) (b : Str) : Result Bool := do
  Shared1A.Insts.CoreCmpPartialOrdShared0B.lt Str.Insts.CoreCmpPartialOrdStr a
    b

/-- [tqlmate_extract::pure::check_strict_order]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 425:4-436:1
    Visibility: public -/
@[rust_loop_body]
def pure.check_strict_order_loop.body
  (files : Slice pure.MigrationId) (applied : Slice pure.Version)
  (max : pure.Version) (i : Std.Usize) :
  Result (ControlFlow Std.Usize (core.result.Result Unit
    pure.StrictOrderError))
  := do
  let i1 := Slice.len files
  if i < i1
  then
    let mi ← Slice.index_usize files i
    let pending ← pure.Version.Insts.CoreCloneClone.clone mi.version
    let b ← pure.version_in applied pending
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else
      let s ← pure.Version.as_str pending
      let s1 ← pure.Version.as_str max
      let b1 ← pure.str_lt s s1
      if b1
      then
        ok (done (core.result.Result.Err (pure.StrictOrderError.OutOfOrder
          pending max)))
      else let i2 ← i + 1#usize
           ok (cont i2)
  else ok (done (core.result.Result.Ok ()))

/-- [tqlmate_extract::pure::check_strict_order]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 425:4-436:1
    Visibility: public -/
@[rust_loop]
def pure.check_strict_order_loop
  (files : Slice pure.MigrationId) (applied : Slice pure.Version)
  (max : pure.Version) (i : Std.Usize) :
  Result (core.result.Result Unit pure.StrictOrderError)
  := do
  loop
    (fun i1 => pure.check_strict_order_loop.body files applied max i1)
    i

/-- [tqlmate_extract::pure::check_strict_order]:
    Source: 'src/../../../src/pure.rs', lines 416:0-436:1
    Visibility: public -/
def pure.check_strict_order
  (files : Slice pure.MigrationId) (applied : Slice pure.Version) :
  Result (core.result.Result Unit pure.StrictOrderError)
  := do
  let o ← pure.max_version applied
  match o with
  | none => ok (core.result.Result.Ok ())
  | some m => pure.check_strict_order_loop files applied m 0#usize

/-- [tqlmate_extract::pure::slugify]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 462:4-472:5
    Visibility: public -/
@[rust_loop_body]
def pure.slugify_loop.body
  (bytes : Slice Std.U8) (out : String) (i : Std.Usize) :
  Result (ControlFlow (String × Std.Usize) String)
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let c ← Slice.index_usize bytes i
    let b ← pure.is_ascii_alnum_byte c
    let out1 ←
      if b
      then
        do
        let lower ← pure.ascii_lower c
        let c1 ← Char.Insts.CoreConvertFromU8.from lower
        alloc.string.String.push out c1
      else
        do
        let s ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref out
        let b1 ← pure.ends_with_underscore s
        if b1
        then ok out
        else alloc.string.String.push out '_'
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [tqlmate_extract::pure::slugify]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 462:4-472:5
    Visibility: public -/
@[rust_loop]
def pure.slugify_loop
  (out : String) (bytes : Slice Std.U8) (i : Std.Usize) : Result String := do
  loop
    (fun (out1, i1) => pure.slugify_loop.body bytes out1 i1)
    (out, i)

/-- [tqlmate_extract::pure::slugify]:
    Source: 'src/../../../src/pure.rs', lines 458:0-479:1
    Visibility: public -/
def pure.slugify («name» : Str) : Result String := do
  let out ← alloc.string.String.new
  let bytes ← core.str.Str.as_bytes «name»
  let out1 ← pure.slugify_loop out bytes 0#usize
  let s ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref out1
  let trimmed ← pure.trim_underscores s
  let b ← core.str.Str.is_empty trimmed
  if b
  then
    alloc.string.String.Insts.CoreConvertFromShared0Str.from (toStr
      "migration")
  else alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay trimmed

/-- [tqlmate_extract::pure::find_label]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 505:4-512:1 -/
@[rust_loop_body]
def pure.find_label_loop.body
  (files : Slice pure.MigrationId) (v : pure.Version) (i : Std.Usize) :
  Result (ControlFlow Std.Usize (Option String))
  := do
  let i1 := Slice.len files
  if i < i1
  then
    let mi ← Slice.index_usize files i
    let b ← pure.Version.Insts.CoreCmpPartialEqVersion.eq mi.version v
    if b
    then let s ← pure.MigrationId.label mi
         ok (done (some s))
    else let i2 ← i + 1#usize
         ok (cont i2)
  else ok (done none)

/-- [tqlmate_extract::pure::find_label]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 505:4-512:1 -/
@[rust_loop]
def pure.find_label_loop
  (files : Slice pure.MigrationId) (v : pure.Version) (i : Std.Usize) :
  Result (Option String)
  := do
  loop
    (fun i1 => pure.find_label_loop.body files v i1)
    i

/-- [tqlmate_extract::pure::find_label]:
    Source: 'src/../../../src/pure.rs', lines 503:0-512:1 -/
@[reducible]
def pure.find_label
  (files : Slice pure.MigrationId) (v : pure.Version) :
  Result (Option String)
  := do
  pure.find_label_loop files v 0#usize

/-- [tqlmate_extract::pure::dump_header]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 488:8-497:9
    Visibility: public -/
@[rust_loop_body]
def pure.dump_header_loop.body
  (applied : Slice pure.Version) (files : Slice pure.MigrationId)
  (out : String) (i : Std.Usize) :
  Result (ControlFlow (String × Std.Usize) String)
  := do
  let i1 := Slice.len applied
  if i < i1
  then
    let v ← Slice.index_usize applied i
    let out1 ← alloc.string.String.push_str out (toStr "--   ")
    let o ← pure.find_label files v
    let out2 ←
      match o with
      | none =>
        do
        let s ← pure.Version.as_str v
        alloc.string.String.push_str out1 s
      | some label =>
        do
        let s ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref label
        alloc.string.String.push_str out1 s
    let out3 ← alloc.string.String.push out2 '
'
    let i2 ← i + 1#usize
    ok (cont (out3, i2))
  else ok (done out)

/-- [tqlmate_extract::pure::dump_header]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 488:8-497:9
    Visibility: public -/
@[rust_loop]
def pure.dump_header_loop
  (applied : Slice pure.Version) (files : Slice pure.MigrationId)
  (out : String) (i : Std.Usize) :
  Result String
  := do
  loop
    (fun (out1, i1) => pure.dump_header_loop.body applied files out1 i1)
    (out, i)

/-- [tqlmate_extract::pure::dump_header]:
    Source: 'src/../../../src/pure.rs', lines 482:0-501:1
    Visibility: public -/
def pure.dump_header
  (applied : Slice pure.Version) (files : Slice pure.MigrationId) :
  Result String
  := do
  let out ←
    alloc.string.String.Insts.CoreConvertFromShared0Str.from (toStr
      "-- Schema dumped by tqlmate\n-- Applied migrations:\n")
  let b ← core.slice.Slice.is_empty applied
  if b
  then
    let out1 ← alloc.string.String.push_str out (toStr "--   (none)\n")
    alloc.string.String.push out1 '
'
  else
    let out1 ← pure.dump_header_loop applied files out 0#usize
    alloc.string.String.push out1 '
'

/-- [tqlmate_extract::pure::strip_dump_header]: loop body 1:
    Source: 'src/../../../src/pure.rs', lines 523:8-525:9
    Visibility: public -/
@[rust_loop_body]
def pure.strip_dump_header_loop0_loop0.body
  (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    if i2 != 10#u8
    then let i3 ← i + 1#usize
         ok (cont i3)
    else ok (done i)
  else ok (done i)

/-- [tqlmate_extract::pure::strip_dump_header]: loop 1:
    Source: 'src/../../../src/pure.rs', lines 523:8-525:9
    Visibility: public -/
@[rust_loop]
def pure.strip_dump_header_loop0_loop0
  (bytes : Slice Std.U8) (i : Std.Usize) : Result Std.Usize := do
  loop
    (fun i1 => pure.strip_dump_header_loop0_loop0.body bytes i1)
    i

/-- [tqlmate_extract::pure::strip_dump_header]: loop body 0:
    Source: 'src/../../../src/pure.rs', lines 521:4-543:5
    Visibility: public -/
@[rust_loop_body]
def pure.strip_dump_header_loop0.body
  (text : Str) (bytes : Slice Std.U8) (started : Bool) (out : String)
  (first : Bool) (i : Std.Usize) :
  Result (ControlFlow (Bool × String × Bool × Std.Usize) String)
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← pure.strip_dump_header_loop0_loop0 bytes i
    let line ←
      Str.Insts.CoreOpsIndexIndex.index
        core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr text
        { start := i, «end» := i2 }
    let i3 := Slice.len bytes
    let i4 ← if i2 < i3
               then i2 + 1#usize
               else ok i2
    if started
    then
      let out1 ← if first
                   then ok out
                   else alloc.string.String.push out '
'
      let out2 ← alloc.string.String.push_str out1 line
      ok (cont (true, out2, false, i4))
    else
      let t ← pure.trim_spaces line
      let b ← core.str.Str.is_empty t
      if b
      then ok (cont (false, out, first, i4))
      else
        let b1 ← pure.has_prefix t (toStr "--")
        if b1
        then ok (cont (false, out, first, i4))
        else
          let out1 ←
            if first
            then ok out
            else alloc.string.String.push out '
'
          let out2 ← alloc.string.String.push_str out1 line
          ok (cont (true, out2, false, i4))
  else ok (done out)

/-- [tqlmate_extract::pure::strip_dump_header]: loop 0:
    Source: 'src/../../../src/pure.rs', lines 521:4-543:5
    Visibility: public -/
@[rust_loop]
def pure.strip_dump_header_loop0
  (text : Str) (started : Bool) (out : String) (first : Bool)
  (bytes : Slice Std.U8) (i : Std.Usize) :
  Result String
  := do
  loop
    (fun (started1, out1, first1, i1) => pure.strip_dump_header_loop0.body text
      bytes started1 out1 first1 i1)
    (started, out, first, i)

/-- [tqlmate_extract::pure::strip_dump_header]:
    Source: 'src/../../../src/pure.rs', lines 515:0-545:1
    Visibility: public -/
def pure.strip_dump_header (text : Str) : Result String := do
  let out ← alloc.string.String.new
  let bytes ← core.str.Str.as_bytes text
  pure.strip_dump_header_loop0 text false out true bytes 0#usize

end tqlmate_extract
