-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tqlmate_extract]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import TqlmateExtract.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open tqlmate_extract

/-- [core::char::convert::{impl core::convert::From<u8> for char}::from]:
    Source: '/rustc/library/core/src/char/convert.rs', lines 229:4-229:26
    Name pattern: [core::char::convert::{core::convert::From<char, u8>}::from]
    Visibility: public -/
@[rust_fun "core::char::convert::{core::convert::From<char, u8>}::from"]
axiom Char.Insts.CoreConvertFromU8.from : Std.U8 → Result Char

/-- [core::cmp::impls::{impl core::cmp::PartialOrd<&'_0 B> for &'_1 A}::lt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2417:8-2417:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::fmt::{impl core::fmt::Display for str}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2981:4-2981:50
    Name pattern: [core::fmt::{core::fmt::Display<str>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Display<str>}::fmt"]
axiom Str.Insts.CoreFmtDisplay.fmt
  :
  Str → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2868:4-2868:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2882:4-2882:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [core::str::{str}::len]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 155:4-155:36
    Name pattern: [core::str::{str}::len]
    Visibility: public -/
@[rust_fun "core::str::{str}::len"]
axiom core.str.Str.len : Str → Result Std.Usize

/-- [core::str::{str}::is_empty]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 175:4-175:40
    Name pattern: [core::str::{str}::is_empty]
    Visibility: public -/
@[rust_fun "core::str::{str}::is_empty"]
axiom core.str.Str.is_empty : Str → Result Bool

/-- [core::str::{str}::as_bytes]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 514:4-514:41
    Name pattern: [core::str::{str}::as_bytes]
    Visibility: public -/
@[rust_fun "core::str::{str}::as_bytes"]
axiom core.str.Str.as_bytes : Str → Result (Slice Std.U8)

/-- [core::str::traits::{impl core::cmp::PartialEq<str> for str}::eq]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 29:4-29:37
    Name pattern: [core::str::traits::{core::cmp::PartialEq<str, str>}::eq]
    Visibility: public -/
@[rust_fun "core::str::traits::{core::cmp::PartialEq<str, str>}::eq"]
axiom Str.Insts.CoreCmpPartialEqStr.eq : Str → Str → Result Bool

/-- [core::str::traits::{impl core::cmp::PartialOrd<str> for str}::partial_cmp]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 48:4-48:58
    Name pattern: [core::str::traits::{core::cmp::PartialOrd<str, str>}::partial_cmp]
    Visibility: public -/
@[rust_fun "core::str::traits::{core::cmp::PartialOrd<str, str>}::partial_cmp"]
axiom Str.Insts.CoreCmpPartialOrdStr.partial_cmp
  : Str → Str → Result (Option Ordering)

/-- [core::str::traits::{impl core::ops::index::Index<I, Clause0_Output> for str}::index]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 62:4-62:43
    Name pattern: [core::str::traits::{core::ops::index::Index<str, @I, @Clause0_Output>}::index]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::ops::index::Index<str, @I, @Clause0_Output>}::index"]
axiom Str.Insts.CoreOpsIndexIndex.index
  {I : Type} {Clause0_Output : Type}
  (sliceindexSliceIndexIStrClause0_OutputInst : core.slice.index.SliceIndex I
  Str Clause0_Output) :
  Str → I → Result Clause0_Output

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::Range<usize>}::index_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 251:4-251:60
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::index_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::index_mut"]
axiom core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.index_mut
  : core.ops.range.Range Std.Usize → Str → Result (Str × (Str → Str))

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::Range<usize>}::index]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 247:4-247:48
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::index]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::index"]
axiom core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.index
  : core.ops.range.Range Std.Usize → Str → Result Str

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::Range<usize>}::get_unchecked_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 227:4-227:75
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get_unchecked_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get_unchecked_mut"]
axiom
  core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked_mut
  : core.ops.range.Range Std.Usize → MutRawPtr Str → Result (MutRawPtr Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::Range<usize>}::get_unchecked]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 199:4-199:75
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get_unchecked]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get_unchecked"]
axiom
  core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked
  :
  core.ops.range.Range Std.Usize → ConstRawPtr Str → Result (ConstRawPtr
    Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::Range<usize>}::get_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 194:4-194:66
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get_mut"]
axiom core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_mut
  :
  core.ops.range.Range Std.Usize → Str → Result ((Option Str) × (Option
    Str → Str))

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::Range<usize>}::get]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 190:4-190:54
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::Range<usize>, str, str>}::get"]
axiom core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexStrStr.get
  : core.ops.range.Range Std.Usize → Str → Result (Option Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeTo<usize>}::index_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 461:4-461:60
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::index_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::index_mut"]
axiom
  core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.index_mut
  : core.ops.range.RangeTo Std.Usize → Str → Result (Str × (Str → Str))

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeTo<usize>}::index]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 453:4-453:48
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::index]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::index"]
axiom core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.index
  : core.ops.range.RangeTo Std.Usize → Str → Result Str

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeTo<usize>}::get_unchecked_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 448:4-448:75
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get_unchecked_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get_unchecked_mut"]
axiom
  core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked_mut
  :
  core.ops.range.RangeTo Std.Usize → MutRawPtr Str → Result (MutRawPtr Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeTo<usize>}::get_unchecked]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 443:4-443:75
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get_unchecked]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get_unchecked"]
axiom
  core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked
  :
  core.ops.range.RangeTo Std.Usize → ConstRawPtr Str → Result (ConstRawPtr
    Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeTo<usize>}::get_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 433:4-433:66
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get_mut"]
axiom core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_mut
  :
  core.ops.range.RangeTo Std.Usize → Str → Result ((Option Str) × (Option
    Str → Str))

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeTo<usize>}::get]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 423:4-423:54
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, str, str>}::get"]
axiom core.ops.range.RangeToUsize.Insts.CoreSliceIndexSliceIndexStrStr.get
  : core.ops.range.RangeTo Std.Usize → Str → Result (Option Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeFrom<usize>}::index_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 532:4-532:60
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::index_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::index_mut"]
axiom
  core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.index_mut
  :
  core.ops.range.RangeFrom Std.Usize → Str → Result (Str × (Str → Str))

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeFrom<usize>}::index]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 524:4-524:48
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::index]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::index"]
axiom core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.index
  : core.ops.range.RangeFrom Std.Usize → Str → Result Str

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeFrom<usize>}::get_unchecked_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 518:4-518:75
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get_unchecked_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get_unchecked_mut"]
axiom
  core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked_mut
  :
  core.ops.range.RangeFrom Std.Usize → MutRawPtr Str → Result (MutRawPtr
    Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeFrom<usize>}::get_unchecked]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 512:4-512:75
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get_unchecked]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get_unchecked"]
axiom
  core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_unchecked
  :
  core.ops.range.RangeFrom Std.Usize → ConstRawPtr Str → Result
    (ConstRawPtr Str)

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeFrom<usize>}::get_mut]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 502:4-502:66
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get_mut]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get_mut"]
axiom
  core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get_mut
  :
  core.ops.range.RangeFrom Std.Usize → Str → Result ((Option Str) ×
    (Option Str → Str))

/-- [core::str::traits::{impl core::slice::index::SliceIndex<str, str> for core::ops::range::RangeFrom<usize>}::get]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 492:4-492:54
    Name pattern: [core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get]
    Visibility: public -/
@[rust_fun
  "core::str::traits::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, str, str>}::get"]
axiom core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexStrStr.get
  : core.ops.range.RangeFrom Std.Usize → Str → Result (Option Str)

/-- [alloc::string::{impl core::cmp::PartialEq<alloc::string::String> for alloc::string::String}::eq]:
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [alloc::string::{core::cmp::PartialEq<alloc::string::String, alloc::string::String>}::eq]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::cmp::PartialEq<alloc::string::String, alloc::string::String>}::eq"]
axiom alloc.string.String.Insts.CoreCmpPartialEqString.eq
  : String → String → Result Bool

/-- [alloc::string::{impl core::cmp::Ord for alloc::string::String}::cmp]:
    Source: '/rustc/library/alloc/src/string.rs', lines 350:36-350:39
    Name pattern: [alloc::string::{core::cmp::Ord<alloc::string::String>}::cmp]
    Visibility: public -/
@[rust_fun "alloc::string::{core::cmp::Ord<alloc::string::String>}::cmp"]
axiom alloc.string.String.Insts.CoreCmpOrd.cmp
  : String → String → Result Ordering

/-- [alloc::string::{alloc::string::String}::new]:
    Source: '/rustc/library/alloc/src/string.rs', lines 446:4-446:32
    Name pattern: [alloc::string::{alloc::string::String}::new]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::new"]
axiom alloc.string.String.new : Result String

/-- [alloc::string::{alloc::string::String}::push_str]:
    Source: '/rustc/library/alloc/src/string.rs', lines 1104:4-1104:44
    Name pattern: [alloc::string::{alloc::string::String}::push_str]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::push_str"]
axiom alloc.string.String.push_str : String → Str → Result String

/-- [alloc::string::{alloc::string::String}::push]:
    Source: '/rustc/library/alloc/src/string.rs', lines 1432:4-1432:36
    Name pattern: [alloc::string::{alloc::string::String}::push]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::push"]
axiom alloc.string.String.push : String → Char → Result String

/-- [alloc::string::{alloc::string::String}::as_bytes]:
    Source: '/rustc/library/alloc/src/string.rs', lines 1461:4-1461:41
    Name pattern: [alloc::string::{alloc::string::String}::as_bytes]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::as_bytes"]
axiom alloc.string.String.as_bytes : String → Result (Slice Std.U8)

/-- [alloc::string::{alloc::string::String}::is_empty]:
    Source: '/rustc/library/alloc/src/string.rs', lines 1896:4-1896:40
    Name pattern: [alloc::string::{alloc::string::String}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::is_empty"]
axiom alloc.string.String.is_empty : String → Result Bool

/-- [alloc::string::{impl core::clone::Clone for alloc::string::String}::clone]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2388:4-2388:27
    Name pattern: [alloc::string::{core::clone::Clone<alloc::string::String>}::clone]
    Visibility: public -/
@[rust_fun "alloc::string::{core::clone::Clone<alloc::string::String>}::clone"]
axiom alloc.string.String.Insts.CoreCloneClone.clone : String → Result String

/-- [alloc::string::{impl core::fmt::Debug for alloc::string::String}::fmt]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2756:4-2756:60
    Name pattern: [alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt]
    Visibility: public -/
@[rust_fun "alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt"]
axiom alloc.string.String.Insts.CoreFmtDebug.fmt
  :
  String → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [alloc::string::{impl core::ops::index::Index<I, Clause0_Output> for alloc::string::String}::index]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2838:4-2838:43
    Name pattern: [alloc::string::{core::ops::index::Index<alloc::string::String, @I, @Clause0_Output>}::index]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::ops::index::Index<alloc::string::String, @I, @Clause0_Output>}::index"]
axiom alloc.string.String.Insts.CoreOpsIndexIndex.index
  {I : Type} {Clause0_Output : Type}
  (coresliceindexSliceIndexIStrClause0_OutputInst : core.slice.index.SliceIndex
  I Str Clause0_Output) :
  String → I → Result Clause0_Output

/-- [alloc::string::{impl core::ops::deref::Deref<str> for alloc::string::String}::deref]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2859:4-2859:27
    Name pattern: [alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref"]
axiom alloc.string.String.Insts.CoreOpsDerefDerefStr.deref
  : String → Result Str

/-- [alloc::string::{impl alloc::string::ToString for T}::to_string]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2930:4-2930:33
    Name pattern: [alloc::string::{alloc::string::ToString<@T>}::to_string]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::ToString<@T>}::to_string"]
axiom alloc.string.ToString.Blanket.to_string
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) : T → Result String

/-- [alloc::string::{impl core::convert::From<&'_0 str> for alloc::string::String}::from]:
    Source: '/rustc/library/alloc/src/string.rs', lines 3150:4-3150:30
    Name pattern: [alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from"]
axiom alloc.string.String.Insts.CoreConvertFromShared0Str.from
  : Str → Result String

