-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tqlmate_extract]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace tqlmate_extract

/-- [tqlmate_extract::pure::Version]
    Source: 'src/../../../src/pure.rs', lines 11:0-11:31
    Visibility: public -/
@[reducible]
def pure.Version := String

/-- [tqlmate_extract::pure::MigrationId]
    Source: 'src/../../../src/pure.rs', lines 25:0-28:1
    Visibility: public -/
structure pure.MigrationId where
  version : pure.Version
  «name» : String

/-- [tqlmate_extract::pure::MigrationStatus]
    Source: 'src/../../../src/pure.rs', lines 41:0-44:1
    Visibility: public -/
@[discriminant isize]
inductive pure.MigrationStatus where
| Applied : pure.MigrationStatus
| Pending : pure.MigrationStatus

/-- [tqlmate_extract::pure::ParseError]
    Source: 'src/../../../src/pure.rs', lines 47:0-53:1
    Visibility: public -/
@[discriminant isize]
inductive pure.ParseError where
| Extension : pure.ParseError
| Filename : pure.ParseError
| VersionDigits : pure.ParseError
| Name : pure.ParseError
| Markers : pure.ParseError

/-- [tqlmate_extract::pure::StrictOrderError]
    Source: 'src/../../../src/pure.rs', lines 56:0-61:1
    Visibility: public -/
@[discriminant isize]
inductive pure.StrictOrderError where
| OutOfOrder : pure.Version → pure.Version → pure.StrictOrderError

/-- [tqlmate_extract::pure::Section]
    Source: 'src/../../../src/pure.rs', lines 64:0-67:1 -/
@[discriminant isize]
inductive pure.Section where
| Up : pure.Section
| Down : pure.Section

end tqlmate_extract
