-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tqlmate_extract]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace tqlmate_extract

/-- [tqlmate_extract::pure::Version]
    Source: 'src/../../../src/pure.rs', lines 14:0-14:31
    Visibility: public -/
@[reducible]
def pure.Version := String

/-- [tqlmate_extract::pure::MigrationId]
    Source: 'src/../../../src/pure.rs', lines 28:0-31:1
    Visibility: public -/
structure pure.MigrationId where
  version : pure.Version
  «name» : String

/-- [tqlmate_extract::pure::MigrationStatus]
    Source: 'src/../../../src/pure.rs', lines 44:0-47:1
    Visibility: public -/
@[discriminant isize]
inductive pure.MigrationStatus where
| Applied : pure.MigrationStatus
| Pending : pure.MigrationStatus

/-- [tqlmate_extract::pure::ParseError]
    Source: 'src/../../../src/pure.rs', lines 50:0-56:1
    Visibility: public -/
@[discriminant isize]
inductive pure.ParseError where
| Extension : pure.ParseError
| Filename : pure.ParseError
| VersionDigits : pure.ParseError
| Name : pure.ParseError
| Markers : pure.ParseError

/-- [tqlmate_extract::pure::StrictOrderError]
    Source: 'src/../../../src/pure.rs', lines 59:0-64:1
    Visibility: public -/
@[discriminant isize]
inductive pure.StrictOrderError where
| OutOfOrder : pure.Version → pure.Version → pure.StrictOrderError

/-- [tqlmate_extract::pure::Section]
    Source: 'src/../../../src/pure.rs', lines 67:0-70:1 -/
@[discriminant isize]
inductive pure.Section where
| Up : pure.Section
| Down : pure.Section

/-- [tqlmate_extract::pure::MigrationSpec]
    Source: 'src/../../../src/pure.rs', lines 526:0-531:1
    Visibility: public -/
structure pure.MigrationSpec where
  version : pure.Version
  «name» : String
  up : String
  down : String

/-- [tqlmate_extract::pure::Op]
    Source: 'src/../../../src/pure.rs', lines 545:0-548:1
    Visibility: public -/
@[discriminant isize]
inductive pure.Op where
| ApplyUp : pure.Version → String → pure.Op
| ApplyDown : pure.Version → String → pure.Op

/-- [tqlmate_extract::pure::State]
    Source: 'src/../../../src/pure.rs', lines 555:0-557:1
    Visibility: public -/
structure pure.State where
  applied : alloc.vec.Vec pure.Version

/-- [tqlmate_extract::pure::PlanError]
    Source: 'src/../../../src/pure.rs', lines 573:0-578:1
    Visibility: public -/
@[discriminant isize]
inductive pure.PlanError where
| EmptyUp : pure.Version → pure.PlanError
| EmptyDown : pure.Version → String → pure.PlanError
| MissingFile : pure.Version → pure.PlanError
| StrictOrder : pure.Version → pure.Version → pure.PlanError

/-- [tqlmate_extract::pure::StepError]
    Source: 'src/../../../src/pure.rs', lines 582:0-585:1
    Visibility: public -/
@[discriminant isize]
inductive pure.StepError where
| EmptyUp : pure.Version → pure.StepError
| EmptyDown : pure.Version → pure.StepError

end tqlmate_extract
